//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class score
    {
        public int id { get; set; }
        public string content_id { get; set; }
        public decimal score1 { get; set; }
        public System.DateTime time_stamp { get; set; }
    }
}
